### ISSUE TITLE
flask auth ==13 not supported anymore. 

### ISSUE THREAD

**Issue by PhilippeH1967** [IntuitDeveloper/SampleApp-QuickBooksV3API-Python#5]
Pip can t install :  Could not find a version that satisfies the requirement Flask_OAuth==0.13 (from versions: 0.9, 0.10, 0.11, 0.12)
No matching distribution found for Flask_OAuth==0.13
Isit mandatory or 12 version is ok ?

**Comment by nbhambhani** [comment]
Thanks for reporting this @PhilippeH1967 . We've removed support for OAuth1 altogether, so this shouldn't be an issue anymore.
