### ISSUE TITLE
Error when running app.py

### ISSUE THREAD

**Issue by PhilippeH1967** [IntuitDeveloper/SampleApp-QuickBooksV3API-Python#6]
Hi
I have this error 👎 
  File "app.py", line 2, in <module>
    from flask_oauth import OAuth
  File "/Users/philippehaumesser/anaconda/lib/python3.6/site-packages/flask_oauth.py", line 13, in <module>
    from urlparse import urljoin
ModuleNotFoundError: No module named 'urlparse'

thanks for help

**Comment by PhilippeH1967** [comment]
Find solution : replace code in flask_oauth 👍 

from urllib.parse import urljoin

**Comment by nbhambhani** [comment]
Thanks for reporting this @PhilippeH1967 . We've removed support for OAuth1 altogether, so this shouldn't be an issue anymore.
